dependencies {
	compileOnly group: "com.liferay.portal", name: "com.liferay.util.taglib", version: "default"
	compileOnly project(":apps:frontend-taglib:frontend-taglib")
}

deploy {
	doFirst {
		delete file(liferay.deployDir)
	}

	liferay {
		deployDir = new File("${rootDir}/dxp/apps/osb/osb-faro/build/deploy")
	}
}