analytics.cloud.client.js.version=DEV
analytics.cloud.domain.allowed=*
passwords.default.policy.changeable=false
terms.of.use.required=false
users.reminder.queries.custom.question.enabled=false
users.reminder.queries.enabled=false
virtual.hosts.valid.hosts=*
