account-admin-web
account-api
account-lang
account-rest-api
account-rest-impl
account-service
adaptive-media-api
adaptive-media-blogs-editor-configuration
adaptive-media-blogs-item-selector-web
adaptive-media-blogs-web-fragment
adaptive-media-blogs-web
adaptive-media-content-transformer-api
adaptive-media-content-transformer-impl
adaptive-media-demo-data-creator-api
adaptive-media-demo-data-creator-impl
adaptive-media-document-library-item-selector-web
adaptive-media-document-library-thumbnails
adaptive-media-document-library-web
adaptive-media-document-library
adaptive-media-image-api
adaptive-media-image-content-transformer-backwards-compatibility
adaptive-media-image-content-transformer
adaptive-media-image-impl
adaptive-media-image-item-selector-api
adaptive-media-image-item-selector-impl
adaptive-media-image-js-web
adaptive-media-image-service
adaptive-media-image-taglib
adaptive-media-image-web
adaptive-media-item-selector-upload-web
adaptive-media-journal-editor-configuration
adaptive-media-journal-web
adaptive-media-test-util
adaptive-media-upload
adaptive-media-web
address-impl
alloy-mvc
analytics-api
analytics-client-osgi
analytics-data-binding-impl
analytics-message-sender-api
analytics-message-sender-impl
analytics-message-storage-api
analytics-message-storage-service
analytics-settings-api
analytics-settings-impl
analytics-settings-web
analytics-web
announcements-api
announcements-uad
announcements-web
app-builder-api
app-builder-lang
app-builder-rest-api
app-builder-rest-client
app-builder-rest-impl
app-builder-service
app-builder-web
application-list-api
application-list-my-account-permissions
application-list-taglib
application-list-user-personal-site-permissions
amazon-rankings-web
chat-api
chat-service
chat-web
currency-converter-api
currency-converter-web
dictionary-web
directory-web
document-library-file-rank-api
document-library-file-rank-service
frontend-editor-simple-web
frontend-editor-tinymce-web
google-maps-web
html-preview-api
html-preview-processor-image
html-preview-service
journal-content-search-web
loan-calculator-web
mail-reader-api
mail-reader-service
mail-reader-web
network-utilities-web
oauth-api
oauth-service
oauth-web
opensocial-portlet
password-generator-web
portal-security-wedeploy-auth-api
portal-security-wedeploy-auth-service
portal-security-wedeploy-auth-web
powwow-portlet
quick-note-web
recent-documents-web
social-activity-web
social-group-statistics-web
social-requests-web
social-user-statistics-web
sync-api
sync-oauth
sync-security
sync-service
sync-web
tasks-portlet
translator-web
unit-converter-web
weather-web
web-form-web
web-proxy-web
wysiwyg-web
xsl-content-web
youtube-web
asset-api
asset-auto-tagger-api
asset-auto-tagger-google-cloud-natural-language-api
asset-auto-tagger-google-cloud-natural-language-impl
asset-auto-tagger-opennlp-api
asset-auto-tagger-opennlp-impl
asset-auto-tagger-service
asset-auto-tagger-web
asset-browser-web
asset-categories-admin-web-api
asset-categories-admin-web
asset-categories-api
asset-categories-item-selector-api
asset-categories-item-selector-web
asset-categories-navigation-api
asset-categories-navigation-web
asset-categories-selector-web
asset-categories-service
asset-category-property-api
asset-category-property-service
asset-display-page-api
asset-display-page-item-selector-api
asset-display-page-item-selector-web
asset-display-page-service
asset-display-web
asset-entry-query-processor-custom-user-attributes
asset-entry-rel-api
asset-entry-rel-service
asset-info-api
asset-info-display-api
asset-info-display-impl
asset-info-impl
asset-link-service
asset-list-api
asset-list-item-selector-web
asset-list-service
asset-list-web
asset-publisher-api
asset-publisher-layout-prototype
asset-publisher-web
asset-service
asset-taglib
asset-tags-admin-web
asset-tags-api
asset-tags-compiler-web
asset-tags-navigation-api
asset-tags-navigation-web
asset-tags-selector-web
asset-tags-service
asset-test-util
asset-web
batch-engine-api
batch-engine-service
bean-portlet-api
bean-portlet-cdi-extension
bean-portlet-extension-api
bean-portlet-registration-api
bean-portlet-registration-impl
blogs-api
blogs-editor-configuration
blogs-item-selector-api
blogs-item-selector-web
blogs-layout-prototype
blogs-reading-time
blogs-recent-bloggers-api
blogs-recent-bloggers-web
blogs-service
blogs-test-util
blogs-uad
blogs-web
bookmarks-api
bookmarks-service
bookmarks-test-util
bookmarks-uad
bookmarks-web
bulk-rest-api
bulk-rest-client
bulk-rest-impl
bulk-selection-api
bulk-selection-impl
calendar-api
calendar-service
calendar-test-util
calendar-web
captcha-api
captcha-impl
captcha-taglib
change-tracking-api
change-tracking-service
change-tracking-spi
change-tracking-store-api
change-tracking-store-service
change-tracking-test-util
change-tracking-web
changeset-api
changeset-service
comment-analytics
comment-api
comment-editor-configuration
comment-page-comments-web
comment-ratings-definition
comment-sanitizer
comment-taglib
comment-web
commerce-account-admin-web
commerce-account-api
commerce-account-group-admin-web
commerce-account-item-selector-api
commerce-account-item-selector-web
commerce-account-service
commerce-account-test-util
commerce-account-web
commerce-address-content-web
commerce-address-web
commerce-api
commerce-application-list
commerce-availability-estimate-web
commerce-cart-content-web
commerce-cart-taglib
commerce-catalog-web
commerce-channel-web
commerce-checkout-web
commerce-currency-api
commerce-currency-service
commerce-currency-test-util
commerce-currency-web
commerce-discount-api
commerce-discount-content-web
commerce-discount-service
commerce-elasticsearch7
commerce-frontend-api
commerce-frontend-impl
commerce-frontend-js
commerce-frontend-taglib
commerce-geocoder-bing
commerce-google-merchant
commerce-health-status-web
commerce-initializer-util
commerce-inventory-api
commerce-inventory-service
commerce-inventory-web
commerce-item-selector-api
commerce-item-selector-web
commerce-lang
commerce-media-api
commerce-media-impl
commerce-notification-api
commerce-notification-service
commerce-notification-test-util
commerce-notification-web
commerce-order-content-web
commerce-order-web
commerce-payment-api
commerce-payment-method-authorize-net
commerce-payment-method-mercanet
commerce-payment-method-money-order
commerce-payment-method-paypal
commerce-payment-service
commerce-payment-test-util
commerce-payment-web
commerce-price-list-api
commerce-price-list-service
commerce-pricing-api
commerce-pricing-service
commerce-pricing-web
commerce-product-api
commerce-product-asset-categories-navigation-web
commerce-product-asset-categories-web
commerce-product-content-api
commerce-product-content-category-web
commerce-product-content-search-web
commerce-product-content-web
commerce-product-ddm-api
commerce-product-ddm-impl
commerce-product-definitions-web
commerce-product-item-selector-api
commerce-product-item-selector-web
commerce-product-measurement-unit-web
commerce-product-options-web
commerce-product-service
commerce-product-subscription-type-web
commerce-product-taglib
commerce-product-tax-category-web
commerce-product-test-util
commerce-product-type-grouped-api
commerce-product-type-grouped-service
commerce-product-type-grouped-web
commerce-product-type-simple
commerce-product-type-virtual-api
commerce-product-type-virtual-order-api
commerce-product-type-virtual-order-content-web
commerce-product-type-virtual-order-service
commerce-product-type-virtual-service
commerce-product-type-virtual-test-util
commerce-product-type-virtual-web
commerce-service
commerce-shipment-content-web
commerce-shipment-web
commerce-shipping-engine-fedex
commerce-shipping-engine-fixed-api
commerce-shipping-engine-fixed-service
commerce-shipping-engine-fixed-web
commerce-shipping-origin-locator-api
commerce-shipping-origin-locator
commerce-shipping-web
commerce-subscription-web
commerce-taglib
commerce-tax-api
commerce-tax-engine-fixed-api
commerce-tax-engine-fixed-service
commerce-tax-engine-fixed-web
commerce-tax-service
commerce-tax-web
commerce-test-util
commerce-theme-minium-api
commerce-theme-minium-impl
commerce-theme-minium-site-initializer
commerce-theme-minium
commerce-theme-speedwell-site-initializer
commerce-theme-speedwell
commerce-warehouse-web
commerce-wish-list-api
commerce-wish-list-service
commerce-wish-list-web
headless-commerce-core-api
headless-commerce-core-impl
headless-commerce-admin-account-api
headless-commerce-admin-account-client
headless-commerce-admin-account-impl
headless-commerce-admin-catalog-api
headless-commerce-admin-catalog-client
headless-commerce-admin-catalog-impl
headless-commerce-admin-channel-api
headless-commerce-admin-channel-client
headless-commerce-admin-channel-impl
headless-commerce-admin-inventory-api
headless-commerce-admin-inventory-client
headless-commerce-admin-inventory-impl
headless-commerce-admin-order-api
headless-commerce-admin-order-client
headless-commerce-admin-order-impl
headless-commerce-admin-pricing-api
headless-commerce-admin-pricing-client
headless-commerce-admin-pricing-impl
headless-commerce-admin-site-setting-api
headless-commerce-admin-site-setting-client
headless-commerce-admin-site-setting-impl
headless-commerce-delivery-cart-api
headless-commerce-delivery-cart-client
headless-commerce-delivery-cart-impl
headless-commerce-delivery-catalog-api
headless-commerce-delivery-catalog-client
headless-commerce-delivery-catalog-impl
configuration-admin-api
configuration-admin-web
connected-app-api
connected-app-web
contacts-api
contacts-service
contacts-uad
contacts-web
content-dashboard-api
content-dashboard-journal-impl
content-dashboard-web
data-cleanup
data-engine-api
data-engine-lang
data-engine-rest-api
data-engine-rest-client
data-engine-rest-impl
data-engine-service
data-engine-taglib
depot-api
depot-service
depot-web
dispatch-api
dispatch-lang
dispatch-service
dispatch-talend-web
dispatch-web
document-library-google-docs
document-library-opener-api
document-library-opener-google-drive-api
document-library-opener-google-drive-web
document-library-opener-service
document-library-opener-uad
document-library-analytics
document-library-api
document-library-asset-auto-tagger-google-cloud-vision
document-library-asset-auto-tagger-microsoft-cognitive-services
document-library-asset-auto-tagger-tensorflow
document-library-content-api
document-library-content-service
document-library-document-conversion
document-library-google-drive-api
document-library-google-drive-impl
document-library-item-selector-web
document-library-layout-set-prototype
document-library-preview-audio
document-library-preview-document
document-library-preview-image
document-library-preview-lang
document-library-repository-authorization-api
document-library-repository-cmis-api
document-library-repository-cmis-impl
document-library-repository-external-api
document-library-repository-portlet-file-repository-impl
document-library-repository-portlet-repository-impl
document-library-repository-search
document-library-service
document-library-sync-api
document-library-sync-service
document-library-taglib
document-library-test-util
document-library-uad
document-library-video
document-library-web
dynamic-data-lists-api
dynamic-data-lists-lang
dynamic-data-lists-service
dynamic-data-lists-web
dynamic-data-mapping-api
dynamic-data-mapping-data-provider-impl
dynamic-data-mapping-data-provider-instance
dynamic-data-mapping-data-provider-web
dynamic-data-mapping-expression
dynamic-data-mapping-form-analytics
dynamic-data-mapping-form-builder
dynamic-data-mapping-form-evaluator-impl
dynamic-data-mapping-form-field-type-api
dynamic-data-mapping-form-field-type
dynamic-data-mapping-form-item-selector-api
dynamic-data-mapping-form-renderer
dynamic-data-mapping-form-report-web
dynamic-data-mapping-form-taglib
dynamic-data-mapping-form-values-factory
dynamic-data-mapping-form-values-query
dynamic-data-mapping-form-web
dynamic-data-mapping-lang
dynamic-data-mapping-service
dynamic-data-mapping-spi
dynamic-data-mapping-taglib
dynamic-data-mapping-test-util
dynamic-data-mapping-uad
dynamic-data-mapping-validator
dynamic-data-mapping-web
expando-api
expando-export-import
expando-taglib
expando-web
export-import-api
export-import-changeset-api
export-import-changeset-service
export-import-changeset-taglib
export-import-changeset-web
export-import-resources-importer
export-import-service
export-import-test-util
export-import-web
external-reference-api
external-reference-service
flags-api
flags-service
flags-taglib
flags-web
fragment-api
fragment-collection-contributor-basic-component
fragment-collection-contributor-featured-content
fragment-collection-contributor-footers
fragment-collection-contributor-navigation-bars
fragment-entry-processor-api
fragment-entry-processor-background-image
fragment-entry-processor-drop-zone
fragment-entry-processor-editable
fragment-entry-processor-freemarker
fragment-entry-processor-impl
fragment-entry-processor-nullable
fragment-entry-processor-portlet
fragment-entry-processor-resources
fragment-impl
fragment-item-selector-api
fragment-renderer-collection-asset-categories-filter-impl
fragment-renderer-menu-display-impl
fragment-renderer-react-impl
fragment-service
fragment-taglib
fragment-web
friendly-url-api
friendly-url-service
frontend-css-common
frontend-css-rtl-servlet
frontend-css-variables-api
frontend-css-variables-web
frontend-css-web
frontend-editor-alloyeditor-web
frontend-editor-api
frontend-editor-ckeditor-web
frontend-editor-lang
frontend-editor-taglib
frontend-js-alert-support-web
frontend-js-aui-web
frontend-js-bundle-config-extender
frontend-js-collapse-support-web
frontend-js-components-web
frontend-js-dropdown-support-web
frontend-js-jquery-web
frontend-js-loader-modules-extender-api
frontend-js-loader-modules-extender
frontend-js-lodash-web
frontend-js-metal-web
frontend-js-minifier
frontend-js-node-shims
frontend-js-portlet-extender
frontend-js-react-web
frontend-js-recharts
frontend-js-spa-web
frontend-js-svg4everybody-web
frontend-js-tabs-support-web
frontend-js-tooltip-support-web
frontend-js-top-head-extender-api
frontend-js-top-head-extender
frontend-js-web
frontend-taglib-chart-sample-web
frontend-taglib-chart
frontend-taglib-clay-sample-web
frontend-taglib-clay
frontend-taglib-dynamic-section
frontend-taglib-form-navigator
frontend-taglib-react
frontend-taglib-soy
frontend-taglib-util-freemarker-contributor
frontend-taglib-util
frontend-taglib
frontend-theme-admin
frontend-theme-browser-support
frontend-theme-classic-style-guide-sample-web
frontend-theme-classic
frontend-theme-contributor-extender
frontend-theme-favicon-servlet
frontend-theme-font-awesome-web
frontend-theme-styled
frontend-theme-unstyled
frontend-token-definition-api
frontend-token-definition-impl
gogo-shell-web
headless-admin-content-api
headless-admin-content-client
headless-admin-content-impl
headless-admin-taxonomy-api
headless-admin-taxonomy-client
headless-admin-taxonomy-impl
headless-admin-user-api
headless-admin-user-client
headless-admin-user-impl
headless-admin-workflow-api
headless-admin-workflow-client
headless-admin-workflow-impl
headless-batch-engine-api
headless-batch-engine-impl
headless-common-spi
headless-delivery-api
headless-delivery-client
headless-delivery-impl
headless-discovery-impl
headless-discovery-web
headless-form-api
headless-form-client
headless-form-impl
headless-portal-instances-api
headless-portal-instances-impl
hello-velocity-web
hello-world-web
iframe-web
image-uploader-web
imageio-plugins
info-api
info-impl
info-list-provider-item-selector-api
info-list-provider-item-selector-web
info-taglib
invitation-invite-members-api
invitation-invite-members-service
invitation-invite-members-web
item-selector-api
item-selector-criteria-api
item-selector-criteria-impl
item-selector-editor-configuration
item-selector-impl
item-selector-taglib
item-selector-upload-web
item-selector-url-web
item-selector-web
journal-api
journal-article-dynamic-data-mapping-form-field-type-api
journal-article-dynamic-data-mapping-form-field-type
journal-content-asset-addon-entry-api
journal-content-asset-addon-entry-comments
journal-content-asset-addon-entry-conversions
journal-content-asset-addon-entry-locales
journal-content-asset-addon-entry-print
journal-content-asset-addon-entry-ratings
journal-content-asset-addon-entry-related-assets
journal-content-web
journal-editor-configuration
journal-item-selector-api
journal-item-selector-web
journal-lang
journal-ratings-definition
journal-service
journal-taglib
journal-terms-of-use
journal-test-util
journal-uad
journal-web
knowledge-base-api
knowledge-base-editor-configuration
knowledge-base-item-selector-api
knowledge-base-item-selector-web
knowledge-base-markdown-converter-api
knowledge-base-markdown-converter-impl
knowledge-base-service
knowledge-base-web
layout-admin-api
layout-admin-web
layout-api
layout-content-page-editor-api
layout-content-page-editor-impl
layout-content-page-editor-web
layout-display-page-api
layout-display-page-impl
layout-dynamic-data-mapping-form-field-type-api
layout-dynamic-data-mapping-form-field-type
layout-impl
layout-item-selector-api
layout-item-selector-web
layout-page-template-admin-api
layout-page-template-admin-web
layout-page-template-api
layout-page-template-service
layout-prototype-api
layout-prototype-impl
layout-seo-api
layout-seo-service
layout-seo-web
layout-service
layout-set-prototype-api
layout-set-prototype-impl
layout-set-prototype-web
layout-taglib
layout-test-util
layout-type-controller-api
layout-type-controller-asset-display
layout-type-controller-collection
layout-type-controller-content
layout-type-controller-control-panel
layout-type-controller-display-page
layout-type-controller-embedded
layout-type-controller-full-page-application
layout-type-controller-link-to-page
layout-type-controller-node
layout-type-controller-panel
layout-type-controller-portlet
layout-type-controller-url
layout-uad
license-manager-web
login-authentication-facebook-connect-web
login-authentication-openid-connect-web
login-authentication-opensso-web
login-web-api
login-web
map-api
map-common
map-google-maps
map-openstreetmap
map-taglib
marketplace-api
marketplace-app-manager-web
marketplace-service
marketplace-store-web
mentions-api
mentions-service
mentions-web
message-boards-api
message-boards-comment
message-boards-editor-configuration
message-boards-layout-set-prototype
message-boards-parser-bbcode
message-boards-service
message-boards-test-util
message-boards-uad
message-boards-web
microblogs-api
microblogs-service
microblogs-web
microsoft-translator
mobile-device-rules-api
mobile-device-rules-service
mobile-device-rules-web
monitoring-lang
monitoring-web
my-subscriptions-web
nested-portlets-web
notifications-uad
notifications-web
oauth2-provider-api
oauth2-provider-jsonws
oauth2-provider-rest-spi
oauth2-provider-rest
oauth2-provider-scope-api
oauth2-provider-scope-impl
oauth2-provider-scope-liferay-api
oauth2-provider-scope-liferay-spi
oauth2-provider-scope-spi
oauth2-provider-service
oauth2-provider-shortcut
oauth2-provider-web
organizations-api
organizations-item-selector-api
organizations-item-selector-web
organizations-service
password-policies-admin-api
password-policies-admin-impl
password-policies-admin-uad
password-policies-admin-web
petra-content
petra-content
petra-doulos
petra-encryptor
petra-encryptor
petra-io-delta
petra-json-validator
petra-json-web-service-client
petra-log4j
petra-log4j
petra-mail-template
petra-mail
petra-mail
petra-model-adapter
petra-xml
petra-xml
plugins-admin-web
polls-api
polls-service
polls-web
portal-background-task-api
portal-background-task-service
portal-background-task-web
portal-cache-api
portal-cache-ehcache-impl
portal-cache-impl
portal-cache-multiple
portal-cache-test-util
portal-configuration-cluster
portal-configuration-extender
portal-configuration-metatype-definitions-annotations
portal-configuration-metatype-definitions-equinox
portal-configuration-module-configuration
portal-configuration-settings
portal-configuration-test-util
portal-configuration-upgrade-api
portal-configuration-upgrade-impl
portal-instances-api
portal-instances-service
portal-instances-web
portal-language-extender
portal-language-servlet-filter
portal-lock-api
portal-lock-service
portal-mobile-device-recognition-impl
portal-model-relationship-document-library-impl
portal-model-relationship-dynamic-data-mapping-impl
portal-odata-api
portal-odata-impl
portal-osgi-debug-api
portal-osgi-debug-declarative-service
portal-osgi-debug-impl
portal-osgi-debug-spring-extender
portal-relationship-api
portal-relationship-impl
portal-remote-axis-extender
portal-remote-cors-api
portal-remote-cors-impl
portal-remote-cxf-common
portal-remote-http-tunnel-extender
portal-remote-http-whiteboard-debug
portal-remote-jaxrs-security-impl
portal-remote-jaxrs-whiteboard-debug
portal-remote-jaxrs-whiteboard-jaxb-json
portal-remote-jaxrs-whiteboard
portal-remote-json-web-service-extender
portal-remote-rest-extender
portal-remote-soap-extender-api
portal-remote-soap-extender-impl
portal-reports-engine-api
portal-rules-engine-api
portal-rules-engine-wiring
portal-scheduler-multiple
portal-scheduler-quartz
portal-scheduler
portal-scripting-api
portal-scripting-executor
portal-scripting-groovy-context-api
portal-scripting-groovy
portal-scripting-impl
portal-search-elasticsearch7-api
portal-search-elasticsearch7-impl
portal-search-elasticsearch7-spi
portal-search-admin-web
portal-search-api
portal-search-engine-adapter-api
portal-search-spi
portal-search-test-util
portal-search-web-api
portal-search-web
portal-search
portal-security-audit-api
portal-security-audit-event-generators-api
portal-security-audit-event-generators-user-management
portal-security-audit-impl
portal-security-audit-router
portal-security-audit-storage-api
portal-security-audit-storage-service
portal-security-audit-wiring
portal-security-sso-google-api
portal-security-sso-google-impl
portal-security-sso-google-login-authentication-web
portal-security-sso-google-settings-authentication-web
portal-security-sso-ntlm-api
portal-security-sso-ntlm-impl
portal-security-sso-ntlm-settings-authentication-web
portal-security-sso-cas-api
portal-security-sso-cas-impl
portal-security-sso-facebook-connect-api
portal-security-sso-facebook-connect-impl
portal-security-sso-openid-connect-api
portal-security-sso-openid-connect-impl
portal-security-sso-opensso-api
portal-security-sso-opensso-impl
portal-security-sso-token-api
portal-security-sso-token-impl
portal-security-antisamy
portal-security-api
portal-security-auth-verifier
portal-security-auto-login
portal-security-export-import-api
portal-security-ldap-api
portal-security-ldap-impl
portal-security-permission-api
portal-security-permission-impl
portal-security-permission-test-util
portal-security-service-access-policy-api
portal-security-service-access-policy-service
portal-security-service-access-policy-web
portal-security-service-access-quota-api
portal-settings-api
portal-settings-authentication-cas-web
portal-settings-authentication-facebook-connect-web
portal-settings-authentication-ldap-web
portal-settings-authentication-openid-connect-web
portal-settings-authentication-opensso-web
portal-settings-authentication-token-web
portal-settings-lang
portal-settings-web
portal-store-db
portal-store-file-system
portal-store-s3
portal-store-test-util
portal-template-freemarker
portal-template-react-renderer-api
portal-template-react-renderer-impl
portal-template-soy-renderer-api
portal-template-soy-renderer-impl
portal-template-velocity
portal-template-xsl
portal-url-builder-api
portal-url-builder-impl
portal-validation-api
portal-vulcan-api
portal-vulcan-impl
portal-workflow-api
portal-workflow-kaleo-api
portal-workflow-kaleo-definition-api
portal-workflow-kaleo-definition-impl
portal-workflow-kaleo-runtime-api
portal-workflow-kaleo-runtime-form-impl
portal-workflow-kaleo-runtime-impl
portal-workflow-kaleo-runtime-integration-impl
portal-workflow-kaleo-runtime-scripting-impl
portal-workflow-kaleo-service
portal-workflow-lang
portal-workflow-metrics-sla-api
portal-workflow-task-web
portal-workflow-uad
portal-workflow-web
portal-aop-api
portal-aop-impl
portal-async-advice
portal-cluster-multiple
portal-compound-session-id
portal-custom-jsp-bag-api
portal-dao-orm-custom-sql-api
portal-dao-orm-custom-sql-impl
portal-db-partition
portal-error-code
portal-executor
portal-fragment-bundle-watcher
portal-inactive-request-handler
portal-init-servlet-filter
portal-instance-lifecycle-api
portal-instance-lifecycle-impl
portal-jmx-api
portal-jmx
portal-license-deployer
portal-local-service-tree-test-util
portal-messaging
portal-monitoring
portal-notifications-test-util
portal-output-stream-container-api
portal-output-stream-container
portal-pop-notifications
portal-spring-extender-api
portal-spring-extender-impl
portal-uad
portal-upgrade-impl
portal-upload-servlet-request-filter
portal-upload
portal-user-locale-options-web
portal-verify-extender
portal-verify-test-util
portal-weblogic-support
portlet-configuration-css-web
portlet-configuration-icon-locator-impl
portlet-configuration-icon-close
portlet-configuration-icon-edit-defaults
portlet-configuration-icon-edit-guest
portlet-configuration-icon-edit
portlet-configuration-icon-help
portlet-configuration-icon-maximize
portlet-configuration-icon-minimize
portlet-configuration-icon-print
portlet-configuration-icon-refresh
portlet-configuration-sharing-web
portlet-configuration-toolbar-contributor-locator-impl
portlet-configuration-web
portlet-dependency-factory-impl
portlet-display-template-api
portlet-display-template-impl
portlet-display-template-web
product-navigation-applications-menu-api
product-navigation-applications-menu-web
product-navigation-control-menu-api
product-navigation-control-menu-impl
product-navigation-control-menu-theme-contributor
product-navigation-control-menu-web
product-navigation-control-panel
product-navigation-personal-menu-api
product-navigation-personal-menu-web
product-navigation-product-menu-api
product-navigation-product-menu-impl
product-navigation-product-menu-theme-contributor
product-navigation-product-menu-web
product-navigation-simulation-api
product-navigation-simulation-device
product-navigation-simulation-theme-contributor
product-navigation-simulation-web
product-navigation-site-administration
product-navigation-taglib
product-navigation-user-personal-bar-web
push-notifications-api
push-notifications-sender-apple
push-notifications-sender-firebase
push-notifications-sender-microsoft
push-notifications-sender-sms
push-notifications-service
push-notifications-web
questions-web
ratings-analytics
ratings-api
ratings-page-ratings-web
ratings-service
ratings-taglib
ratings-test-util
reading-time-api
reading-time-editor-plugin
reading-time-service
reading-time-taglib
reading-time-web
redirect-api
redirect-service
redirect-web
remote-app-admin-web
remote-app-api
remote-app-service
remote-app-support-web
remote-app-uad
roles-admin-api
roles-admin-impl
roles-admin-web
roles-item-selector-api
roles-item-selector-web
roles-selector-web
roles-uad
rss-api
rss-impl
rss-taglib
rss-web
screens-api
screens-service
segments-api
segments-content-targeting-upgrade
segments-context-vocabulary
segments-lang
segments-service
segments-simulation-web
segments-test-util
segments-web
server-admin-web
sharing-api
sharing-blogs
sharing-document-library
sharing-lang
sharing-notifications
sharing-search
sharing-service
sharing-taglib
sharing-test-util
sharing-web
site-navigation-admin-api
site-navigation-admin-web
site-navigation-api
site-navigation-breadcrumb-web
site-navigation-directory-web
site-navigation-item-selector-api
site-navigation-item-selector-web
site-navigation-lang
site-navigation-language-api
site-navigation-language-web
site-navigation-menu-item-api
site-navigation-menu-item-layout
site-navigation-menu-item-node
site-navigation-menu-item-url
site-navigation-menu-web
site-navigation-service
site-navigation-site-map-web
site-navigation-taglib
site-admin-web
site-api
site-browser-web
site-impl
site-insurance-site-initializer
site-item-selector-api
site-item-selector-web
site-memberships-api
site-memberships-web
site-my-sites-web
site-service
site-taglib
site-teams-uad
site-teams-web
social-bookmarks-hook
social-activities-api
social-activities-taglib
social-activities-web
social-activity-api
social-activity-impl
social-activity-test-util
social-bookmark-facebook
social-bookmark-linkedin
social-bookmark-twitter
social-bookmarks-analytics
social-bookmarks-api
social-bookmarks-taglib
social-user-statistics-api
staging-api
staging-bar-web
staging-configuration-web
staging-impl
staging-lang
staging-portlet-data-handler
staging-processes-web
staging-taglib
osgi-felix-lang
osgi-log-service-extender
osgi-util
portal-bundle-blacklist-api
portal-bundle-blacklist-impl
portal-component-blacklist-api
portal-component-blacklist-impl
portal-configuration-metatype-api
portal-configuration-persistence-api
portal-configuration-persistence-impl
portal-dependency-manager-component-executor-factory
portal-file-install-api
portal-file-install-impl
portal-lpkg-deployer-api
portal-lpkg-deployer-impl
portal-lpkg-deployer-test-util
portal-osgi-web-jasper-plugins-taglib
portal-osgi-web-portlet-container-test-util
portal-osgi-web-portlet-tracker
portal-osgi-web-servlet-api
portal-osgi-web-servlet-context-helper-api
portal-osgi-web-servlet-context-helper-impl
portal-osgi-web-servlet-el-api-fragment
portal-osgi-web-servlet-jsp-api-fragment
portal-osgi-web-servlet-jsp-compiler
portal-osgi-web-wab-extender
portal-osgi-web-wab-generator-api
portal-osgi-web-wab-generator-impl
portal-osgi-web-wab-reference-support
portal-osgi-web-wab-spring-bridge-api
portal-change-tracking
portal-classloader-tracker
portal-log4j-extender
portal-profile-api
portal-profile-impl
portal-social-activity-extender
portal-upgrade-api
required-dependencies
style-book-api
style-book-service
style-book-web
subscription-api
subscription-service
subscription-test-util
subscription-web
text-localizer-address-api
text-localizer-taglib
translation-api
translation-service
translation-web
trash-api
trash-service
trash-taglib
trash-test-util
trash-web
upload-api
upload-web
user-associated-data-api
user-associated-data-test-util
user-associated-data-web
user-groups-admin-api
user-groups-admin-impl
user-groups-admin-item-selector-api
user-groups-admin-item-selector-web
user-groups-admin-uad
user-groups-admin-web
users-admin-api
users-admin-impl
users-admin-item-selector-api
users-admin-item-selector-web
users-admin-test-util
users-admin-uad
users-admin-web
view-count-api
view-count-service
websocket-whiteboard
wiki-api
wiki-editor-configuration
wiki-editor-link-browse-web
wiki-engine-creole
wiki-engine-html
wiki-engine-input-editor-common
wiki-engine-lang
wiki-engine-text
wiki-layout-prototype
wiki-navigation-web
wiki-service
wiki-test-util
wiki-uad
wiki-web
xstream-configurator-api
jaxws-osgi-bridge
osgi-service-tracker-collections
petra-concurrent
petra-concurrent
petra-executor
petra-executor
petra-function
petra-function
petra-io
petra-io
petra-lang
petra-lang
petra-memory
petra-memory
petra-nio
petra-nio
petra-process
petra-process
petra-reflect
petra-reflect
petra-sql-dsl-api
petra-sql-dsl-api
petra-sql-dsl-spi
petra-sql-dsl-spi
petra-string
petra-string
petra-test-util
petra-test-util
petra-url-pattern-mapper
petra-url-pattern-mapper
portal-app-license-api
portal-app-license-resolver-hook
portal-bootstrap
portal-equinox-log-bridge
registry-api
registry-api
registry-impl
analytics-reports-api
analytics-reports-impl
analytics-reports-journal-impl
analytics-reports-web
antivirus-clamd-scanner
app-builder-workflow-api
app-builder-workflow-lang
app-builder-workflow-rest-api
app-builder-workflow-rest-client
app-builder-workflow-rest-impl
app-builder-workflow-service
app-builder-workflow-web
commerce-avalara-connector-api
commerce-avalara-connector
commerce-avalara-lang
commerce-avalara-tax-engine-fixed-web
commerce-avalara-tax-engine-fixed
commerce-theme-minium-full-site-initializer
commerce-punchout-api
commerce-punchout-lang
commerce-punchout-oauth2-provider-api
commerce-punchout-oauth2-provider-rest
commerce-punchout-portal-security-auto-login
commerce-punchout-service
commerce-punchout-web
headless-commerce-punchout-api
headless-commerce-punchout-impl
commerce-application-admin-web
commerce-application-api
commerce-application-item-selector-api
commerce-application-item-selector-web
commerce-application-service
commerce-bom-admin-web
commerce-bom-api
commerce-bom-service
commerce-bom-web
commerce-dashboard-web
commerce-data-integration-api
commerce-data-integration-service
commerce-data-integration-talend-api
commerce-data-integration-talend
commerce-data-integration-web
commerce-machine-learning-api
commerce-machine-learning-forecast-alert-api
commerce-machine-learning-forecast-alert-lang
commerce-machine-learning-forecast-alert-service
commerce-machine-learning-forecast-alert-web
commerce-machine-learning-impl
commerce-organization-api
commerce-organization-web
commerce-talend-job-deployer-api
commerce-talend-job-deployer-lang
commerce-talend-job-deployer-salesforce
headless-commerce-bom-api
headless-commerce-bom-impl
headless-commerce-machine-learning-api
headless-commerce-machine-learning-impl
document-library-opener-onedrive-web
documentum-hook
frontend-theme-dxp-override
multi-factor-authentication-email-otp-api
multi-factor-authentication-email-otp-service
multi-factor-authentication-email-otp-web
multi-factor-authentication-fido2-credential-api
multi-factor-authentication-fido2-credential-service
multi-factor-authentication-fido2-web
multi-factor-authentication-ip-address-impl
multi-factor-authentication-spi
multi-factor-authentication-timebased-otp-api
multi-factor-authentication-timebased-otp-service
multi-factor-authentication-timebased-otp-web
multi-factor-authentication-web
portal-reports-engine-console-api
portal-reports-engine-console-jasper
portal-reports-engine-console-service
portal-reports-engine-console-web
portal-rules-engine-drools
portal-search-elasticsearch-cross-cluster-replication-impl
portal-search-elasticsearch-monitoring-web
portal-search-learning-to-rank-api
portal-search-learning-to-rank-impl
portal-search-similar-results-web-spi
portal-search-similar-results-web
portal-search-tuning-rankings-web
portal-search-tuning-synonyms-web
portal-search-tuning-web-api
portal-search-tuning-web
portal-security-audit-event-generators
portal-security-audit-lang
portal-security-audit-web
portal-workflow-kaleo-designer-lang
portal-workflow-kaleo-designer-web
portal-workflow-kaleo-forms-api
portal-workflow-kaleo-forms-lang
portal-workflow-kaleo-forms-service
portal-workflow-kaleo-forms-web
portal-workflow-kaleo-metrics-integration
portal-workflow-metrics-api
portal-workflow-metrics-lang
portal-workflow-metrics-rest-api
portal-workflow-metrics-rest-client
portal-workflow-metrics-rest-impl
portal-workflow-metrics-rest-spi
portal-workflow-metrics-service
portal-workflow-metrics-web
portal-dao-db
portal-plugin-deployment-extension
portal-properties-swapper
saml-addon-keep-alive-web
saml-api
saml-hook
saml-impl
saml-opensaml-integration
saml-persistence-api
saml-persistence-service
saml-web
segments-asah-connector
segments-asah-rest-api
segments-asah-rest-client
segments-asah-rest-impl
segments-experiment-web
sharepoint-rest-oauth2-api
sharepoint-rest-oauth2-service
sharepoint-rest-oauth2-web
sharepoint-rest-repository
sharepoint-soap-repository
arquillian-extension-junit-bridge-connector
portal-tools-db-upgrade-client
