/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.analytics.message.storage.service.base;

import com.liferay.analytics.message.storage.model.AnalyticsModelRemoveLogger;
import com.liferay.analytics.message.storage.service.AnalyticsModelRemoveLoggerLocalService;
import com.liferay.analytics.message.storage.service.AnalyticsModelRemoveLoggerLocalServiceUtil;
import com.liferay.analytics.message.storage.service.persistence.AnalyticsModelRemoveLoggerPersistence;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the analytics model remove logger local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.analytics.message.storage.service.impl.AnalyticsModelRemoveLoggerLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.analytics.message.storage.service.impl.AnalyticsModelRemoveLoggerLocalServiceImpl
 * @generated
 */
public abstract class AnalyticsModelRemoveLoggerLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AnalyticsModelRemoveLoggerLocalService, AopService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AnalyticsModelRemoveLoggerLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AnalyticsModelRemoveLoggerLocalServiceUtil</code>.
	 */

	/**
	 * Adds the analytics model remove logger to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AnalyticsModelRemoveLoggerLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param analyticsModelRemoveLogger the analytics model remove logger
	 * @return the analytics model remove logger that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AnalyticsModelRemoveLogger addAnalyticsModelRemoveLogger(
		AnalyticsModelRemoveLogger analyticsModelRemoveLogger) {

		analyticsModelRemoveLogger.setNew(true);

		return analyticsModelRemoveLoggerPersistence.update(
			analyticsModelRemoveLogger);
	}

	/**
	 * Creates a new analytics model remove logger with the primary key. Does not add the analytics model remove logger to the database.
	 *
	 * @param analyticsModelRemoveLoggerId the primary key for the new analytics model remove logger
	 * @return the new analytics model remove logger
	 */
	@Override
	@Transactional(enabled = false)
	public AnalyticsModelRemoveLogger createAnalyticsModelRemoveLogger(
		long analyticsModelRemoveLoggerId) {

		return analyticsModelRemoveLoggerPersistence.create(
			analyticsModelRemoveLoggerId);
	}

	/**
	 * Deletes the analytics model remove logger with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AnalyticsModelRemoveLoggerLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param analyticsModelRemoveLoggerId the primary key of the analytics model remove logger
	 * @return the analytics model remove logger that was removed
	 * @throws PortalException if a analytics model remove logger with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AnalyticsModelRemoveLogger deleteAnalyticsModelRemoveLogger(
			long analyticsModelRemoveLoggerId)
		throws PortalException {

		return analyticsModelRemoveLoggerPersistence.remove(
			analyticsModelRemoveLoggerId);
	}

	/**
	 * Deletes the analytics model remove logger from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AnalyticsModelRemoveLoggerLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param analyticsModelRemoveLogger the analytics model remove logger
	 * @return the analytics model remove logger that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AnalyticsModelRemoveLogger deleteAnalyticsModelRemoveLogger(
		AnalyticsModelRemoveLogger analyticsModelRemoveLogger) {

		return analyticsModelRemoveLoggerPersistence.remove(
			analyticsModelRemoveLogger);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return analyticsModelRemoveLoggerPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AnalyticsModelRemoveLogger.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return analyticsModelRemoveLoggerPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.analytics.message.storage.model.impl.AnalyticsModelRemoveLoggerModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return analyticsModelRemoveLoggerPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.analytics.message.storage.model.impl.AnalyticsModelRemoveLoggerModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return analyticsModelRemoveLoggerPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return analyticsModelRemoveLoggerPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return analyticsModelRemoveLoggerPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AnalyticsModelRemoveLogger fetchAnalyticsModelRemoveLogger(
		long analyticsModelRemoveLoggerId) {

		return analyticsModelRemoveLoggerPersistence.fetchByPrimaryKey(
			analyticsModelRemoveLoggerId);
	}

	/**
	 * Returns the analytics model remove logger with the primary key.
	 *
	 * @param analyticsModelRemoveLoggerId the primary key of the analytics model remove logger
	 * @return the analytics model remove logger
	 * @throws PortalException if a analytics model remove logger with the primary key could not be found
	 */
	@Override
	public AnalyticsModelRemoveLogger getAnalyticsModelRemoveLogger(
			long analyticsModelRemoveLoggerId)
		throws PortalException {

		return analyticsModelRemoveLoggerPersistence.findByPrimaryKey(
			analyticsModelRemoveLoggerId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			analyticsModelRemoveLoggerLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AnalyticsModelRemoveLogger.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"analyticsModelRemoveLoggerId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			analyticsModelRemoveLoggerLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			AnalyticsModelRemoveLogger.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"analyticsModelRemoveLoggerId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			analyticsModelRemoveLoggerLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AnalyticsModelRemoveLogger.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"analyticsModelRemoveLoggerId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return analyticsModelRemoveLoggerPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return analyticsModelRemoveLoggerLocalService.
			deleteAnalyticsModelRemoveLogger(
				(AnalyticsModelRemoveLogger)persistedModel);
	}

	@Override
	public BasePersistence<AnalyticsModelRemoveLogger> getBasePersistence() {
		return analyticsModelRemoveLoggerPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return analyticsModelRemoveLoggerPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the analytics model remove loggers.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.analytics.message.storage.model.impl.AnalyticsModelRemoveLoggerModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of analytics model remove loggers
	 * @param end the upper bound of the range of analytics model remove loggers (not inclusive)
	 * @return the range of analytics model remove loggers
	 */
	@Override
	public List<AnalyticsModelRemoveLogger> getAnalyticsModelRemoveLoggers(
		int start, int end) {

		return analyticsModelRemoveLoggerPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of analytics model remove loggers.
	 *
	 * @return the number of analytics model remove loggers
	 */
	@Override
	public int getAnalyticsModelRemoveLoggersCount() {
		return analyticsModelRemoveLoggerPersistence.countAll();
	}

	/**
	 * Updates the analytics model remove logger in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AnalyticsModelRemoveLoggerLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param analyticsModelRemoveLogger the analytics model remove logger
	 * @return the analytics model remove logger that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AnalyticsModelRemoveLogger updateAnalyticsModelRemoveLogger(
		AnalyticsModelRemoveLogger analyticsModelRemoveLogger) {

		return analyticsModelRemoveLoggerPersistence.update(
			analyticsModelRemoveLogger);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AnalyticsModelRemoveLoggerLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		analyticsModelRemoveLoggerLocalService =
			(AnalyticsModelRemoveLoggerLocalService)aopProxy;

		_setLocalServiceUtilService(analyticsModelRemoveLoggerLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AnalyticsModelRemoveLoggerLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AnalyticsModelRemoveLogger.class;
	}

	protected String getModelClassName() {
		return AnalyticsModelRemoveLogger.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				analyticsModelRemoveLoggerPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		AnalyticsModelRemoveLoggerLocalService
			analyticsModelRemoveLoggerLocalService) {

		try {
			Field field =
				AnalyticsModelRemoveLoggerLocalServiceUtil.class.
					getDeclaredField("_service");

			field.setAccessible(true);

			field.set(null, analyticsModelRemoveLoggerLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected AnalyticsModelRemoveLoggerLocalService
		analyticsModelRemoveLoggerLocalService;

	@Reference
	protected AnalyticsModelRemoveLoggerPersistence
		analyticsModelRemoveLoggerPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}