apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
    labels:
        argocd.argoproj.io/secret-type: repository
    name: {{ .Values.argocdSecretName }}
    namespace: {{ .Values.namespace }}
spec:
    data:
        -   remoteRef:
                key: {{ .Values.remoteSecretKey }}
                property: {{ .Values.gitTokenProperty }}
            secretKey: password
        -   remoteRef:
                key: {{ .Values.remoteSecretKey }}
                property: {{ .Values.gitUsernameProperty }}
            secretKey: username
    refreshInterval: 1h
    secretStoreRef:
        kind: SecretStore
        name: {{ .Values.secretStoreName }}
    target:
        creationPolicy: Owner
        name: {{ .Values.argocdSecretName }}
        template:
            type: Opaque