apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
    name: {{ .Values.secretStoreName }}
    namespace: {{ .Values.namespace }}
spec:
    provider:
        {{ .Values.secretStoreProviderYaml | nindent 8 }}